<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>

<body>
  <script src="./Promise.js"></script>
  <script>
    let p = new Promise((resolve, reject) => {
      setTimeout(() => {
        // resolve('OKOKOK');
        reject('Error');
      }, 2000);
    });

    let result = p.then(
        value => {
            return 123;
        }, error => {
            return new Promise((resolve, reject) => {
                resolve('nono');
            });
            console.log(error);
        } 
    );

    // 这返回的也是一个promise
    p.catch(reason => {
      console.log(reason);
    })

    // 异常穿透   
    p.catch(
      value => {
        return 123;
      }
    ).then(e => {
      console.log(e);
    })

    // 值传递
    p.then(v => {
      console.log(); // 这里的正确方法返回值是undefined
    }).then(() => {
    }).then(() => {
    }).catch(e => {
      console.log(e);
    }) // 值传递 只需要在最后一个catch中处理错误即可 
    
  </script>
</body>

</html>